import AppKit
import IsletCore
import Observation

/// Remembers recent text copies, in memory only: nothing is ever written to disk, and copies that password managers
/// mark as concealed or transient are skipped.
@MainActor
@Observable
final class ClipboardMonitor {
    private(set) var history = ClipboardHistory()
    @ObservationIgnored private var timer: Timer?
    @ObservationIgnored private var lastChange = NSPasteboard.general.changeCount

    /// Markers from nspasteboard.org that password managers and similar apps set on sensitive copies.
    private static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
    ]

    func start() {
        guard timer == nil, Preferences.keepsClipboardHistory else { return }
        // The pasteboard has no change notification. Reading one counter a second, with a generous tolerance so
        // the system can batch the wake-up with others, is the lightest way to follow it.
        let timer = Timer(timeInterval: 1, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.check() }
        }
        timer.tolerance = 0.5
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        history.clear()
    }

    private func check() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChange else { return }
        lastChange = pasteboard.changeCount
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.privateTypes), let text = pasteboard.string(forType: .string) else { return }
        history.add(text, at: Date(), from: NSWorkspace.shared.frontmostApplication?.localizedName)
    }

    /// Puts an entry back on the clipboard, ready to paste.
    func copy(_ entry: ClipboardHistory.Entry) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(entry.text, forType: .string)
        lastChange = pasteboard.changeCount
        history.add(entry.text, at: Date(), from: entry.sourceApp)
    }

    func remove(_ entry: ClipboardHistory.Entry) {
        history.remove(entry.id)
    }

    func clear() {
        history.clear()
    }
}
